---
- name: create user account for all our servers
  hosts: devservers
  become: True
  remote_user: devops
  vars_files:
    - secret.yml
  tasks:
  - name: creating users from secret.yml
    user: 
      name: "{{ username }}"
      password: "{{ pwhash }}"



