---
- name: Using copy module
  hosts: all
  remote_user: root
  tasks:
    - name: Copy module test
      copy:
        src: files/users.txt
        dest: /home/devops/users.txt
        owner: devops
        group: devops
        mode: u_rw,g-wx,o-rwx
        setype: samba_share_t


