---
# tasks file for myvhost
- name: Ensure httpd is installed
  yum:
    name: httpd
    state: latest

- name: Ensuuuuure httpd service is started and enabled
  service:
    name: httpd
    state: started
    enabled: true

- name: VHOST FILE IS INSTALLED
  template:
    src: vhost.conf.j2
    dest: /etc/httpd/conf.d/vhost.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - restart httpd

- name: html content is installed
  copy:
    src: html/
    dest: "/var/www/vhost/{{ ansible_hostname }}"
