---
# tasks file for myfirewall\
- name: Ensure firewalld is installed
  yum:
    name: firewalld
    state: latest

- name: Ensure firealld is started & enabled
  service:
    name: firewalld
    state: started
    enabled: true

- name: Ensure firewalld services are anabled
  firewalld:
    state: enabled
    immediate: true
    permanent: true
    service: "{{ item }}"
  loop: "{{ firewall_services }}"  

    
    
